services:
  postgres:
      image: "postgres:13.3-alpine"
      ports: 
        - 5432:5432
      volumes:
        - postgres_data:/var/lib/postgresql/data
      env_file:
        - .env
      restart: on-failure
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
        interval: 10s
        timeout: 5s
        retries: 3

volumes:
  postgres_data:
